### ISSUE TITLE
Implement "Hide Tabs" API

### ISSUE THREAD

**Issue by Keith94** [Drive4ik/simple-tab-groups#2]
**EDIT:** See https://github.com/Drive4ik/simple-tab-groups/issues/2#issuecomment-368275037 for implementation.

----

Since there's no official API for hiding/showing individual tabs yet, I found this workaround here that works with Nightly: https://github.com/kesselborn/conex#getting-a-version-that-can-really-hide-tabs

I'd love to know if there's a way to make that `hidetabsexperiment.xpi` add-on work together with your Simple Tab Groups? Keeping the tabs loaded is essential for me.

**Comment by TomaszKane** [comment]
+1 vote.

**Comment by kesselborn** [comment]
eh uh ... what have I done: note that this `hidetabsexperiement.xpi` is a hack for testing out stuff and has the problems and implications noted in the README. Furthermore, this will **never** work in Firefox stable ... it'll **always be nightly only** and could stop working any time.
@Drive4ik if you really want to play around with this thing, feel free to ping me.

**Comment by Keith94** [comment]
@kesselborn I didn't test the hack extensively, but it works pretty well from my brief testing. Can it be adapted properly to other extensions such as Simple Tab Groups?

**Comment by kesselborn** [comment]
@Keith94 yes, in the same way as conex does:

- you need to do the `about:config` setting changes
- it only works on the current Nightly (it'll never work on Beta or Stable)
- you will need a dedicated build of your extension if users without the `hidetabsexperiment.xpi` extension should be able to install your extension
- you can not host that build on the official mozilla addon page

... if that is ok, it's easy to do.

The [diff to the normal extension](https://github.com/kesselborn/conex/compare/webext-experiment-showOnlyTheseTabs?expand=1) is pretty small ... the `release` and `versions.json` diff can be ignored.

**Comment by Keith94** [comment]
Thanks for the info. :)

**Comment by Drive4ik** [comment]
Hello everyone.
https://github.com/kesselborn/conex#getting-a-version-that-can-really-hide-tabs
I'll see what I can do

**Comment by Drive4ik** [comment]
This experiment not working in Firefox stable. And now I can't implement this functional. As soon as this functionality is available - I'll start to rewrite the add-on for its support

**Comment by mirh** [comment]
tabHide landed hours ago in nightly.

**Comment by Keith94** [comment]
Hey, that's good to know. Is there a link?

**Comment by mirh** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1423725

**Comment by Keith94** [comment]
So, I'm guessing this is actionable now. Just saw [this addon](https://addons.mozilla.org/firefox/addon/hide-tab/) for tab hiding.

**Comment by Drive4ik** [comment]
This is just great news. 👍
I will soon release an experimental version that supports this API!

**Comment by me21** [comment]
Please make it optional. Won't hiding tabs instead of closing them lead to higher memory usage? Someone might prefer current behaviour.

**Comment by mirh** [comment]
Hiding tabs of course is something user has to specify some way. 
And if somebody does it, then it means it's not something wanted to be closed in the first place.

**Comment by TheLaGmAn** [comment]
Hey @Drive4ik , is there any ETA for this feature? waiting on it to start using this great addon :)

**Comment by Drive4ik** [comment]
Hi all!
Tomorrow or the day after tomorrow will be the first working alpha version

**Comment by adipose** [comment]
I'm currently using the hiding functionality with the addon "totally not panorama."  I prefer the extension "simplified tab groups," which this seems to mimic pretty well, so I'd be happy to have the tab hiding working here.

I disagree that it shouldn't be the default to hide and keep in memory. Panorama always kept these in memory and it is just a way of grouping tabs, not bookmarking them and loading them later.  If they get unloaded, most of the use is gone because it loses the current state of the tab.  You may have to sign back in or lose your scroll position, and it takes longer to reload.

The whole reason we couldn't have panorama on webextensions was the lack of hiding api.  Now some say it should be off by default?  Blasphemy! :)

**Comment by digitalnomad91** [comment]
very nice @adipose. "totally not panorama." is exactly what I want, but I too would prefer to keep the renaming and organizational features in this plugin. I like being able to name and switch between groups with a dropdown. Thanks @Drive4ik, you will be making me very happy after it's done. This is the main feature I was missing when FF switch to Quantum :)

**Comment by digitalnomad91** [comment]
Where we at guys?

**Comment by Drive4ik** [comment]
Hi all!
This is first alpha
https://addons.mozilla.org/en-US/firefox/addon/experimental-simple-tab-groups/
please, read description below this addon

Some functional was deleted, one added (discard tabs), some not working

Thanks

**Comment by hdd60311** [comment]
@Drive4ik
I see it requires 60.0a1, can't it work at 59beta?

**Comment by ccope** [comment]
@hdd60311 yeah odd, the hide-tabs branch in the github repository says 59b10 but the addons site says 60a1.

@Drive4ik could you please push your latest changes to the repository?

**Comment by ccope** [comment]
Ah, I just downloaded and extracted the source. For the curious, based on skimming the source changes, the following features appear to be broken:
 - Moving tabs from one group to another (this is the only thing I saw explicitly in the code, and is the only issue blocking me personally)
 - "Create new group if tab is moved to new window"
 - "Enable fav-icons for not loaded tabs (disable this checkbox if more speed is needed)"
 - "Individual window for each group"
 - "Open group in new window"
 - "Open new window when create new group"

**Comment by Drive4ik** [comment]
@hdd60311 No, it works on FF 59beta, but new changes and new features of hide-tab api will appear on FF nightly. So you do not worry, I think that in the FF 59 stable hide-tab will not work by default, because you need a lot more test.

@ccope 
Now I was pushed this code in repository.
Yes, I removed this functionality due to its uselessness.
When all the functionality is fully implemented, you will not need to open many windows for convenient operation. Although the multi-window functional is preserved.

**Comment by ccope** [comment]
@Drive4ik Yeah most of those things sound reasonable to remove.

Is it possible to make the plugin work in FF59 though? I'd prefer to use a stable (in 2 weeks) browser with the single about:config flag change instead of running an alpha or early beta browser. Is the main problem just https://bugzilla.mozilla.org/show_bug.cgi?id=1398272 ? Could you use https://github.com/piroor/webextensions-lib-tab-id-fixer until the fix is made?

**Comment by Drive4ik** [comment]
Hi all!
I updated [EXPERIMENTAL] Simple Tab Groups addon.
Please tell me - what difficulties / bugs do you experience with this addon.
Do not write about new features, only bugs.

Thanks

**Comment by ccope** [comment]
I tried switching to the new extension. Here's how I hit a bug:
 * Open Firefox (previous session resumes, all of my old tabs from my tabgroup are there)
 * Open some new tabs
 * Switch to a different tab group

The tabs from the tab group appear at the beginning of the tab bar, but the tabs from the previous tab group do not disappear from the tab bar.
 * Switch back to the previous tab group

All new tabs that I opened since I last opened the group are gone.

Maybe there's a bug where no tab group is activated when Firefox is initially opened?

**Comment by ccope** [comment]
Moving tabs between groups seems to work ok, except it can't close the tab if it's the currently active tab (so you end up with a copy of the tab in both groups). Also the pop-up notifications about moves seem unnecessary and they are annoying when you're moving a bunch of tabs.

**Comment by Drive4ik** [comment]
Hi @ccope !
First I want to thank for having pushed me to the idea of fixing the wrong tab id after attach tab (I modify idea of https://github.com/piroor/webextensions-lib-tab-id-fixer)!

About bugs:
> The tabs from the tab group appear at the beginning of the tab bar, but the tabs from the previous tab group do not disappear from the tab bar.
Maybe there's a bug where no tab group is activated when Firefox is initially opened?

Yes. It should be so. This is done for proper synchronization if there is no synchronized group in the window, that is, tabs, and you select another group, then I can not close these tabs. Perhaps I can optionally do this: if there is no synchronized group in the window and you choose any other non-synchronized group, place the current tabs in a new group, and do not move to the one that was selected.

About move active tab to other group: I fix it, please update experimental addon to latest version.

**Comment by nd-** [comment]
Hi,
I just tried your extension on FF Nightly, it looks very promising, very good job, i like it !
At least the same look'n feel as the original Tab group / Panorama.

I just noticed that the extension MySessions doesn't backup all tabs but only the current group.
Even if it did backup all tabs, i'm pretty sure it would be without the groups informations.

Do you know if there is already an extension that can correctly backup all tabs and groups ?
If that doesn't exist yet, maybe you could add a kind of autosave feature to your extension, something like X backups every Y minutes.

Thanks for your work, maybe i'll finally leave my old FF56 and definitly switch to quantum :)

**Comment by ccope** [comment]
@Drive4ik I'm not sure I totally follow your reply about "synchronization". Here's what I expect should happen:
 1. Have one window open, with an active Group_1 with some tabs
 1. Quit Firefox
 1. Open Firefox, Group_1 and its tabs should automatically be active again
 1. Open some tabs in Group_1
 1. Switch to Group_2, and only the tabs from Group_2 are visible
 1. Switch back to Group_1, and all of the tabs opened before the switch, as well as before Firefox was closed, should exist

It sounds like there's a problem in step 3. Can the extension detect that Firefox has just started, and remember the tab group that was active before Firefox closed? Or maybe compare what tabs are visible (excluding pinned tabs and restricted tabs like about:*) with any existing groups?

**Comment by Drive4ik** [comment]
@nd- 
After the full implementation and release of the add-on with the support for hiding tabs, I plan to add a backup to the cloud of the Firefox account, and then you can configure the automatic backup.

@ccope 
Sorry, but I can't understand the problem. Addon save latest opened windows but after restart it has different ids (window id). Can you record your screen with this bug to GIF animation?
http://www.screentogif.com

**Comment by nd-** [comment]
You mean a backup with Firefox Sync ?
Good idea, but I think a simple local backup in the profile would be very usefull too.

**Comment by youk** [comment]
It would be extremely useful. Sometimes when Firefox crashes I end up with all the groups lost. Backup copy would alleviate this. Something basic like what Firefox does for session restore.

**Comment by Drive4ik** [comment]
@nd- Yes it is. But, current webextension capabilities do not allow to make an automatic local copy, only in manual mode through addon settings, or Firefox Sync cloud.

**Comment by nd-** [comment]
OMG ! 😢 
I didn't know...

**Comment by youk** [comment]
@Drive4ik I am wondering how do you make changes to storage.js then

**Comment by Drive4ik** [comment]
@youk  I do not have direct access to storage.json, just using the API
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea/set

**Comment by lp55** [comment]
Hi, any ETA when the experimental version will be merged with the stable one (https://addons.mozilla.org/pt-PT/firefox/addon/simple-tab-groups/)? I have already changed my extensions.webextensions.tabhide.enabled option on Firefox 59 :)
I'm fine with a config option to set the usage from the current default way to the new tab-hide API. I just don't really wanna uninstall my current simple tab groups add-on and install the experimental one. Too many tabs and histories that could be lost...
Thanks for a great add-on by the way! 👍

**Comment by youk** [comment]
@lp55 [Session Boss](https://addons.mozilla.org/en-US/firefox/addon/session-boss/) to the rescue.

**Comment by ccope** [comment]
@lp55 the extension has a button to export and import your session in the settings page.

If anyone is migrating from FF56 Panorama using the backup feature, I did notice that the backup file  was missing tab group ID's for most of the tabs in my active group (which caused the Simple Tab Groups extension to throw a bunch of errors during the restore process).

**Comment by klint** [comment]
Hi. I'm playing/using the Experimental addon and it is quite promising, thanks :)
However, and you have warned us about it so no surprise, there are some issues. I have difficulties to find a pattern though, but when I switch from one group to the other (not using Panorama, but with the menu), or when I close the last tab in a group, weird things happen like a pinned empty tab, or a message about invalid id, or a tab that gets duplicated in a empty group without asking, or... name it :)
I must confess that I have tons of other addons, and I can't remove them as this is my computer at work (I need them). 
Sorry for not being more specific for the moment..

**Comment by fen0x** [comment]
Hi!
I'm using the stable version of this plugin and I was tempted to try this experimental version (moreover, i NEED tab hiding!). So I installed it, disabled the stable plugin and activated the experimental one.
And I get this message:
![snipaste_20180316_191254](https://user-images.githubusercontent.com/1822818/37537753-cc3da9f4-294e-11e8-8170-4c11b04c27ad.png)
And the topmostleft icon, simply does nothing.

I need to tell you that I'm deeply satisfied with the stable version, and I'm actively interested in this project.
Thank you for your work. :)

**Comment by davidyscott** [comment]
I was super excited to try out Firefox 59 and the EXPERIMENTAL plugin, but unfortunately I ran into the same issue as @fen0x 😢

**Comment by Drive4ik** [comment]
Hi all, I fixed bug "windows.some", please update addon to latest version

**Comment by jpfleury** [comment]
This update fixes the bug "windows.some". Thanks a lot. However, I wonder if it's normal that when I select "Refresh all tabs", it refreshes all tabs from all groups instead of only tabs from the current group. It causes problems when a hidden group contains hundreds of tabs.

**Comment by Drive4ik** [comment]
"Refresh all tabs" this is browser functional and not have access to it. I can only add new item in STG tab menu with action like "Reload the displayed tabs"

**Comment by Draghmar** [comment]
I have a question to everyone using experimental build: how do you consider stability of this extension? Is there anything that is still broken and makes overall usage too hard for normal work day? Are there any features still missing to use it on daily basis?
I do understand the 'experimental' nature of this extension but I really would like already start to use it ;)

**Comment by nd-** [comment]
@Draghmar i installed the extension 2 weeks ago.
I'm a web developer and i spend my whole day on Firefox (Nightly), except when i test websites on chrome :p 
I have personal groups, things to read..., and i create a group for each customer or project i'm working on, to be able to quickly switch.
Currently I have 15 groups, between 10 and 20 tabs each, and no crash, no tab lost, no problem since 2 weeks.
I tried Conex and i didn't like the UI and the way it works. I'm very habby with this one :)
Many thanks to @Drive4ik \o/

**Comment by adipose** [comment]
This is the best extension available for this functionality.  It now has the "simplified tab groups" and the Panorama interface both.  The hiding actually works and the shortcuts.  I'm here to stay. :)

**Comment by dgutov** [comment]
Not particularly stable, in my experience. Just after two days of using it, I started getting errors like this when trying to switch to a different tab group:

```
Error: Invalid tab ID: 2
chrome://browser/content/ext-browser.js 0:1
```

With different ID numbers, for different groups. Disabling/enabling the addon didn't fix the situation. it only made the groups' contents mixed up.

**Comment by dgutov** [comment]
> it only made the groups' contents mixed up.

Meaning some tabs were "moved" out of all groups, and some were actually displayed as if belonging to two of them (displayed in both). Thankfully, moving them manually (and closing the duplicates) did the trick. Looks like none of them were actually lost.

I hope this extension starts doing automatic backups soon.

**Comment by klint** [comment]
I have the same symptoms as dgutov actually.

**Comment by Draghmar** [comment]
@Drive4ik Thanks! Will try.
@nd- Thanks, that's exactly what I need this extension for :) It's great to hear that it does what old extension did :D 
I think I will take an adventure here and give a try, even if there can be some issues like @dgutov had described.

**Comment by Draghmar** [comment]
Ok, so I found huge issue with experimental version - there are weird things happen when FF crashes. I do often have some crashes because of the number of tabs and soft I use with the small amount of RAM. I just had this crash and after restarting all the tabs where in one virtual group. There were no groups in Simple Tab Groups, only whole list and some info about non-synchronized groups and what do to with them. I have Session Boss installed but it didn't helped here (BTW if I don't open each group sessions backup managers doesn't get all groups for some reason, at least Session Boss doesn't).

**Comment by Drive4ik** [comment]
@Draghmar 
This is a very complex topic, since the addon does not have data when FF crashes, or when it restores windows and tabs ... so I can not guess what FF is doing at the moment ..
Most likely in the future I'll add a button, something like "fix all", which will try to synchronize everything based on the current state of windows and tabs, and in most cases it will help. you just need to open the popup and press it.

**Comment by Draghmar** [comment]
Yeah, I though it wasn't simple task. ;) I just wanted to report it so people would do backups. If you will do the auto backup you've mentioned before (can't wait for when that ships!) and gives us a way to set the time period for it then it would be great thing to mitigate the problem. As for now I'll just do backup manually from time to time. Especially when I'll manage to guess that FF will crash in a moment - I'm pretty good at this after so many crashes :D.

One thing though - after restoring backup it didn't replace everything but that huge anonymous list ended up glued into group that was opened after restore. I had to close each additional tab manually. If that happens again I will probably start new window and import backup to the clean window.

**Comment by youk** [comment]
@Draghmar It's not the case with the experimental version only. The same thing happens with the regular version.

**Comment by Draghmar** [comment]
Oh, I didn't know that. Regular version doesn't eat so much RAM because of the unloading. So I didn't have any issues with it.

> it should only hide the tabs, right?
Yeah, but it looks like sessions manager don't see the tabs in other groups if the group itself wasn't initialized yet. As if STM didn't start those group until they are needed.

**Comment by dgutov** [comment]
> Error: Invalid tab ID: ...

This just happened again. Restart kind of helps. But afterwards, I saw that the "problem" group (the one I was trying to switch to) got all the tabs from the formerly "current" one added, as duplicates. Had to remove them one by one again.

**Comment by Draghmar** [comment]
Ok, so I just had this weird issue where after starting FF I've got one of my groups copy tabs into another. FF was closed normally. It wasn't crash or anything. Startup was also normal.
What I remember is that yesterday I closed FF having tab X in focus. When I opened FF today it was again this tab X but it was in different group - it was copied along with other from it's group into the other one, which was not active when closing. When I switched to the group from where X originated it behave like it wasn't initialized never before - every tab in this group was reloaded.

**Comment by dgutov** [comment]
@Drive4ik Any chance of dealing with duplicates, at least? I just had this happen twice in a row, the same error right after I restarted and deleted all the duplicates.

I'm guessing the "Invalid tab ID" thing might be a Firefox bug, but the duplicates probably aren't.

**Comment by Draghmar** [comment]
I think I've seen those duplicates too - started FF, were in one of the groups, switch to other, opened some link by clicking from external app, the new tab landed in this other group but at the same time all the tabs from previous group was copied to the switched one.

**Comment by pintassilgo** [comment]
When using tab contextmenu to move the selected tab to another group (let's say from Group 1 to Group 2), this tab should remain selected, changing view to Group 2. What happens now is that the view continues on Group 1, with other tab being selected.

Thanks for this extension, it's the best of the category.

**Comment by dgutov** [comment]
> this tab should remain selected, changing view to Group 2

Disagree (so at most this should be a user option).

**Comment by pintassilgo** [comment]
Well, I think it's intuitive: I didn't select another tab, so currently selected tab should remain selected. And if I moved it to another group, then the view should be changed too.

Noting that this is only when I move the selected tab. If I move a backgrounded tab it should just dissapear.

**Comment by dgutov** [comment]
IDK, I'm personally fine with the current behavior. And group switching is fairly slow anyway.

**Comment by pintassilgo** [comment]
Similarly, when we detach the selected tab, the new window with the tab is opened in foreground, not in background.

**Comment by grssam** [comment]
Look at how file moves are implemented (via context menu "Send to" option). They do not move the current view to the folder/device the file is being sent to.

**Comment by Draghmar** [comment]
My FF just crashed and after starting again restore tabs info was shown - had this already a few times without any issues. But this time there was also an error:
![stg-error](https://user-images.githubusercontent.com/275348/38560739-9aa0f446-3cd6-11e8-864e-78ad7cf04d5a.png)
The STG button at the top doesn't work after that and on the add-on page there are no settings at all only 'Please, update addon to latest version'...which I already have.

**Comment by fen0x** [comment]
Hi!
I'm on Firefox 60.0beta13 and after the last update I get randomly this message when switching groups

![snipaste_20180418_060649](https://user-images.githubusercontent.com/1822818/38911382-238c6788-42cf-11e8-842c-776d7bb96fc0.png)

Then the STG icon is like this and I'm not able to switch to any group

![immagine](https://user-images.githubusercontent.com/1822818/38911403-5af9780a-42cf-11e8-9f42-879fb1d3ff82.png)

The extension works only after restanting FF.

Thank you! :-)

**Comment by Draghmar** [comment]
I have a question. Is there anything I could copy from FF folder to make a backup of the STG settings and current sessions? I thought that before you'll make auto backup I'll do some local auto backup so I wouldn't have to remember to do it manually from settings page each day. ;)

**Comment by Draghmar** [comment]
I had another weird error. I wanted to create a blank tab in different group than I was currently in. I did this on many occasions but this time I've got an error when I tried to switch to this tab:
![stg-error1](https://user-images.githubusercontent.com/275348/39871722-069d4a54-5466-11e8-8c71-957dcc1971ad.png)
After that STG icon changed to spinner:
![stg-error2](https://user-images.githubusercontent.com/275348/39871758-1e65b964-5466-11e8-85b3-934a7c258f60.png)
STG did change the group but changing it back to another one *moved* all the tabs from the faulty one to this new group.
Restarting didn't help. I had to restore from backup.
This was on FF61b3.

**Comment by adipose** [comment]
So, I have been using this for quite some time, and now I am using it on FF60.  Yet, the same bug seems to keep repeating: at some point, all tabs make it into both groups.  I have to manually go through group A and group B, removing A's from B and B's from A.  Not a giant problem, but some sort of bug.

**Comment by Draghmar** [comment]
I've seen that there was an update. Aside from making settings more readable and asking for additional permission, is there a changelog on what else changed?

**Comment by kimsey0** [comment]
I've switched over to [Panorama View](https://github.com/photodiode/panorama-view). Their [tab hiding](https://github.com/photodiode/panorama-view/blob/master/src/js/background.js#L128) seems to work great.

**Comment by Keith94** [comment]
@Draghmar
>Fully refactor UI
Add multiple move tabs in Manage groups by Ctrl+Left click
Add color picker
Other improvements

https://addons.mozilla.org/en-US/firefox/addon/experimental-simple-tab-groups/versions/

**Comment by Drive4ik** [comment]
@Draghmar and @adipose Hi! Can you replicate this problem in latest experimental STG ?

**Comment by Drive4ik** [comment]
@adipose Then you must wait for the release of FF61 Stable :)

**Comment by klint** [comment]
@adipose or FF61Beta which is pretty stable already

**Comment by klint** [comment]
Hi
Still have issues with Invalid Tab Id, either when switching between group, or in the panarama view when clicking on a tab. But again, I have no clear and reproducible pattern to share. Sorry for that.
![image](https://user-images.githubusercontent.com/218971/40840613-bc2297b0-65a7-11e8-8b23-3ae41f64d994.png)

**Comment by adipose** [comment]
@Drive4ik I intend to.  But you didn't answer my question: 

What feature from 61 did it need?

**Comment by Draghmar** [comment]
@Drive4ik The simple one to reproduce, which is opening blank tab through STG menu works right now (awesome!). I will monitor how new STG behaves through the day and let you know if there will be any problem. I did have some issues like the one that opens dummy group with tabs from existing group (the one that was active when FF was closed) after FF restarts and when changing to another group tabs from dummy group are added to the one I switched to.
I also did have some weird issue when after launching (or restarting) FF switching to tab would start the page it was in it and after loading it would redirect content to one of the others tabs I had hidden. It looked like IDs were wrong.

**Comment by Drive4ik** [comment]
@adipose I meant that this assembly will appear as stable only on FF 61, the tab hiding function will be turned on by default. If you are use FF 60 you have to enable tab hiding preference in FF about:config

@Draghmar You have the opportunity to record GIF animation or video, since my English is very weak and sometimes it's hard for me to grasp the essence of the problem. Thanks

**Comment by jpkempf** [comment]
I'm on FF 61 (dev edition), plugin version `2.5.4.1`and I checked to confirm that`extensions.webextensions.tabhide.enabled` is set to `true` under `about:config`. Still, all of my tabs reload every time I switch groups. I am also not getting the warning/hint about tabs being hidden that I get when using Panorama View, for instance, so I'm assuming that no attempt is being made by the addon to hide/unhide any tabs.

The way I think I've understood the discussion here and in other linked issues, this shouldn't be a problem. Am I wrong or am I missing something? Aside from this issue, Simple Tab Groups looks absolutely wonderful and I'd love to be able to use it so I can finally get rid of FF 56, which at the moment I am still using as my main browser because I can't live without Tab Groups. 😂

**Comment by Draghmar** [comment]
@jpkempf Take a loog into settings of STG as there is an option to make reloading permanent. Maybe you have it turned on?
@Drive4ik I could try although most of the issues happens during my work day so I don't always have the time to do it. Anyway I had new/old error. For no reason whatsoever I tried to switch from one group to another and got:
![stg-err-id](https://user-images.githubusercontent.com/275348/40975879-abc4616e-68cc-11e8-9d8a-bf43668ffded.png)
After that it was usual spinning STG icon and I was unable to switch to any group with same error (and ID) for every tab I tried. Restarting FF fixed the issue with the usual addition of the tabs from group that was active when closed to the group I switched after restarting. The group that the tabs where copied from is not loaded at all which means opening it will load all the tabs - very annoying:
![stg-err-reload](https://user-images.githubusercontent.com/275348/40976092-4e58bcf4-68cd-11e8-9ad8-10d70720a5c8.jpg)
BTW I tried this option in settings to get the logs but there was none. The tooltip showed info that no lgos were found.

**Comment by Drive4ik** [comment]
@jpkempf Hi, STG now not supported hide tabs, but [EXPERIMENTAL] Simple Tab Groups supports
https://addons.mozilla.org/firefox/addon/experimental-simple-tab-groups/

**Comment by Drive4ik** [comment]
@Draghmar Thanks, I will try to fix this bug

**Comment by jpkempf** [comment]
@Drive4ik That would definitely explain it—I was under the impression the non-experimental version already had those changes. I'll try out the experimental version, then. Thanks! :)

**Comment by Draghmar** [comment]
@Drive4ik Found another bug of some kind. I was launching FF for the first time this morning and I was already greet with spinning STG icon and error:
![stg-err-startup](https://user-images.githubusercontent.com/275348/41082231-e35674c0-6a2d-11e8-9939-93df43fca810.png)
Clicking an icon didn't do anything. I couldn't invoke the shortcut to overview (it did open new tab but it was empty) and in add-on settings there were not settings at all. Restarting FF didn't. What I did was to disable STG, restart FF and then enable STG again.

**Comment by nd-** [comment]
@Drive4ik Hello, 
after reading "05/26/2018 this addon will be removed and available as a stable version", i made a backup of my groups and tabs, disactivated Experimental STG, and installer STG.
I tried to restore my backup, but it says "Please, update addon to latest version".

I disactivated STG and reactivated Exp STG, and now i have no config, just "Please, update addon to latest version".

But no updates available for Exp STG / STG

Whet can i do ?

Firefox 60.0.2 / Exp STG 3.0.5.1 / STG 2.5.4.1

**Comment by klint** [comment]
All
Just wanted to tell you that the Experimental version has been quite stable since its last update 2 days ago. No more Invalid ID for me so far :)
Thanks @Drive4ik

**Comment by adipose** [comment]
It is confusing on the experimental page, it says "05/26/2018 this addon will be removed and available as a stable version."  But bug fixes are still being rolled out to the experimental, and apparently the tab hiding is not in stable yet, either.  Perhaps that will change with the release of 61.0?

Right now, after going to the experimental page for a fix, reading that, it makes you think you should go straight to the stable, but probably, you shouldn't.

**Comment by adipose** [comment]
I just installed Fx 61.0 and the latest experimental.  All my tabs ended up in both groups, and I couldn't move them between groups.  All I could do was close them, and then they disappeared from both groups.  Then after closing 3-4 of them, I started getting the "invalid tab id" which forced me to restart Fx.  After that, all those that I closed from group 2 showed up in group 2 again, but not group 1.  I was then able to move them.

I'll give this thing one more chance assuming that my having an older build up to today might have put the database in some sort of inconsistent state.  But this behavior has been dogging this extension for a while, and I'm not sure it's getting better.

**Comment by nd-** [comment]
> It is confusing on the experimental page, it says "05/26/2018 this addon will be removed and available as a stable version." But bug fixes are still being rolled out to the experimental, and apparently the tab hiding is not in stable yet, either. 

@adipose Same here, as i said https://github.com/Drive4ik/simple-tab-groups/issues/2#issuecomment-395470161

Very confusing and inappropriate...

**Comment by klint** [comment]
It is really getting better for me, I can tell. But I chose to remove the addon at some point then I reinstalled it immediately, in order to just get a brand new database. This has solved the last issues I had.
And I'm using the experimental version since that day without any issue or almost. :)

**Comment by adipose** [comment]
@klint 
Huh, well I removed it and restarted Fx, and then added it back.  It remembered all my tabs.  So, I'm not sure it was a brand new database...

**Comment by klint** [comment]
You are right... Maybe I just deleted all groups manually at some point, before recreating them. Anyway, it works better now 😊

**Comment by Draghmar** [comment]
@adipose I had similar issue once. I do backups regularly so I just removed addon completely, restarted FF (this is important step), installed it again and bring the backup. It worked after that.

You can tell if there is something wrong with the group after starting FF if you use your own icons for the groups. I've noticed that if the group is dummy one then the icon will be default one and original group will have unloaded tabs. Lately I discovered that if you change group to the same group that your dummy copied tabs from, it will work just fine. If you choose different group you'll most likely end up with tabs from dummy glued to the selected one.

**Comment by Drive4ik** [comment]
Hi @adipose , I can't replicate this behavior https://github.com/Drive4ik/simple-tab-groups/issues/2#issuecomment-400048296 can you replicate and record screen with it?
Thank you

You can use some of these http://www.screentogif.com/ for record screen

**Comment by adipose** [comment]
@klint no, you were right.  the problem was the "remove" button in the settings didn't actually remove the extension.  I had to go to the main extensions screen to remove it.  I thought it was gone but I guess it takes a second to load the icon.

@Draghmar yes, that actually worked and I did observe the behavior you described.  I never had color icons working before now.  The first time I uninstalled it, I did restart, but as I said there seems to be a bug with the "remove" button in the settings.

@Drive4ik Hopefully it won't happen again.  I can recreate the issue, I think, but maybe if I send you my backup you can see the issue.  When restoring the backup, the problem came back.

**Comment by adipose** [comment]
I diffed my backup before and after doing a clean install, and the only thing of significance is that in the new backup, there are two additional settings that weren't there before:

```
    "showGroupIconWhenSearchATab": true,
    "showUrlTooltipOnTabHover": true

```

It's hard to believe this could cause the issue I was having.

**Comment by adipose** [comment]
@Draghmar not a bad theory.  But in the export, there were no repeat ids (1, 6, 7, 8 and 16 in groups 1 and 2).  Yet when I imported it, it went wonky again.

Perhaps it has nothing to do with the import, though.  In the past this issue comes up sporadically and I mostly get it after a Fx restart--but not every restart.

**Comment by Draghmar** [comment]
@adipose I'm not sure if that how FF works but I think FF uses IDs internally and sometimes it changes them which can cause those issues. But that is something @Drive4ik would have to confirm.

I don't the import itself is the problem here. I had problems like that mostly when I had to restart FF because of the memory limits on my computer vs number of active tabs I have open or when FF simply crashed. ;)

**Comment by Draghmar** [comment]
@Drive4ik Am i understand this correctly and you've merged regular version of STG with experimental one? Because I can't find experimental at addon site...Is this means I should remove experimental and install regular one? My version is 3.0.6.5 and I see that there is 3.0.7 already.

**Comment by dgutov** [comment]
@Draghmar That is my understanding too. But you should create a backup of your groups before uninstalling the experimental addon. Because you'll need to restore it after installing the regular one.

**Comment by Keith94** [comment]
I see "invalid tab ID" as well today.

![2018-06-29_13-50-10](https://user-images.githubusercontent.com/5490615/42114320-7d0f61ae-7ba3-11e8-9766-8cd8b5324e5a.png)

**Comment by Drive4ik** [comment]
@Keith94 Hi! Do you have any other extensions that can work with tabs? I can not repeat this problem in any way. You can turn off all extensions, turn on one at a time and try to repeat it?

**Comment by Keith94** [comment]
Not really. The bug happened just by accident. If I figure out how to reproduce, I'll let you know.

**Comment by dgutov** [comment]
Same here: no other tab management extensions (Undo Close Tab probably doesn't count), the bug happens sporadically.

**Comment by dgutov** [comment]
Another thing, hopefully it might help a little: when the bug happens, it leaves a pinned empty tab at the beginning of the tab strip. So after restarting Firefox, I always have to remove it manually.

**Comment by adipose** [comment]
@Drive4ik 
Today I successfully got the invalid tab id.  I restarted Firefox, as that usually fixes it.  But now I get a different invalid tab id.  It is currently doing it, so if you want details from my browser memory, send me a message.

**Comment by adipose** [comment]
Oh, and once it happens the interface for simple-tab-groups disappears from the title bar.

**Comment by Keith94** [comment]
@Drive4ik https://pastebin.com/raw/fMp8660Z

**Comment by adipose** [comment]
[img]https://i.imgur.com/ANd8F3F.png[/img]

**Comment by Drive4ik** [comment]
Hi all! I tried fix bug with invalid tab id. Please wait next release v3.0.10

**Comment by Keith94** [comment]
I guess I can close this. Thanks to all for testing. :)
