### ISSUE TITLE
Found hidden unsynchronized tabs. Click on tab to show it into current group/window or:

### ISSUE THREAD

**Issue by Tyrewt** [Drive4ik/simple-tab-groups#339]
"**Found hidden unsynchronized tabs. Click on tab to show it into current group/window or:**" This message appears where the Manage Groups, Reload Add-on and Gear icon usually are located. None of these options are present, only the message.

I've also noticed all Fav-icons from the group I use the most have disappeared, but all other groups saved the fav-icons, this may not be related.

 - OS and version: Ubuntu 18.04
 - Firefox version: 65.0.1
 - Simple Tab Groups version: 3.4.1

**Comment by Drive4ik** [comment]
Hi. I did not understand the question

**Comment by Tyrewt** [comment]
I believe I submitted as a bug report. Based on other threads, I saw you typically recommend users "Reload Addon", but as indicated, all 3 option icons are missing.

I've since tried Disable/Enable the Addon, the outlined above remains. What would you recommend?

**Comment by Drive4ik** [comment]
Can you make a screenshot of the add-on popup window?

**Comment by Tyrewt** [comment]
The STG window doesn't capture in a screenshot (I tried before submitting). Basically, if you're viewing the STG window, under the "Create new group", the 3 interface options are missing and only **Found hidden unsynchronized tabs. Click on tab to show it into current group/window or:** message appears.

**Comment by Drive4ik** [comment]
![screenshot_1](https://user-images.githubusercontent.com/7843031/53588326-5bedfc80-3b95-11e9-9464-6b9164f5151d.png)
![screenshot_2](https://user-images.githubusercontent.com/7843031/53588329-5db7c000-3b95-11e9-9484-05b2be7bc0eb.png)
![screenshot_3](https://user-images.githubusercontent.com/7843031/53588330-5ee8ed00-3b95-11e9-858e-49002d356fb2.png)
![screenshot_4](https://user-images.githubusercontent.com/7843031/53588332-601a1a00-3b95-11e9-8a39-b1179ee49ee2.png)

**Comment by Tyrewt** [comment]
![screenshot from 2019-02-28 17-21-30](https://user-images.githubusercontent.com/21961083/53602753-b11e1400-3b7d-11e9-9fab-650fa8b7793d.png)

**Comment by Drive4ik** [comment]
No scroll, strange ... Maybe you use userContent.css or some kind of addon that changes the look? I can’t replicate this problem.

**Comment by Tyrewt** [comment]
The only other Add-on I use is uBlock Origin. Guess I'll try an uninstall.

**Comment by Tyrewt** [comment]
Uninstalling the STG Add-on, then reinstalling the options are present. Once I import the tab backup, the icon options are gone. Very odd behavior.

**Comment by Lunatrius** [comment]
Simply closing and opening the browser will desync ALL tabs that were loaded before the browser was closed. It started happening about 2 weeks ago. Since they're all duplicates of tabs that are in groups I can just close/delete them most of the time.

**Comment by Lunatrius** [comment]
I can reproduce it on a fresh profile with only STG installed. using the following versions:

* Firefox 65.0.2
* STG 3.4.1

**Comment by Drive4ik** [comment]
@Lunatrius hi. Can you record screen with your issue?
And tell me what OS you are using?
You can use this app
https://www.screentogif.com/

**Comment by Lunatrius** [comment]
I forgot to mention, it only happens if you have 2 or more Firefox windows open, a rather important detail.

Happens on Windows 10 b1809, Windows 10 Enterprise b1809 and Windows 8.1.

https://puu.sh/CYqSq/bcce03b961.mp4

**Comment by Drive4ik** [comment]
@Lunatrius Hi. Thanks for video, it helped me. I fixed this bug, please update to latest version and retest

**Comment by Tyrewt** [comment]
@Drive4ik @Lunatrius Excellent work, thank you for your contributions.

**Comment by Drive4ik** [comment]
@Tyrewt I can not repeat your problem ...

![изображение](https://user-images.githubusercontent.com/7843031/54221447-34cfed00-44fc-11e9-823f-9a59cd4a836f.png)

**Comment by Tyrewt** [comment]
@Drive4ik Though I was affected by this bug, perhaps the options were present I just didn't scroll down far enough. I'll update this evening with the current release and will report back of not resolved. Let's close this off for now?

> ![screenshot from 2019-02-28 17-21-30](https://user-images.githubusercontent.com/21961083/53602753-b11e1400-3b7d-11e9-9fab-650fa8b7793d.png)

**Comment by Lunatrius** [comment]
No longer have the issue, works flawlessly. Thanks!
