### ISSUE TITLE
"found hidden unsynchronous tabs" menu contains a duplicate of all tabs in all groups at startup

### ISSUE THREAD

**Issue by notJerl** [Drive4ik/simple-tab-groups#347]
When starting Firefox, it will often (not always, but frequently) for some reason dump a duplicate of the entire contents of the previous session into the "found hidden unsynchronous tabs" menu, even tabs which are already in groups, in which case they end up both in their group *and* in the hidden unsynchrous tabs menu.  This gets mixed in with other hidden unsynchronous tabs (tabs opened from links before the add-on finished loading, tabs sent from other devices while the browser was closed, etc), making it extremely difficult to find the handful of non-duplicate hidden unsynchronous tabs amid the cacophony (I currently have about 230 tabs open in 6 groups in 4 windows).  This also makes the add-on initialize very slowly, since it instead has to churn through about 460 tabs.

To reproduce: Restart Firefox.

Expected behavior: Existing tabs from before the restart get put in their correct groups *only* without being duplicated in the hidden unsynchronous tabs menu.

 - OS and version: Windows 7
 - Firefox version: 65.0.2
 - Simple Tab Groups version: 3.4.1

Additional context: The first time this happened was the next restart after a Firefox crash.  The browser recovered from the crash normally.  Tab Groups restored the tabs correctly, but Firefox also gave me the popup asking whether to restore the session or not.  I accidentally clicked "yes", and it duplicated all 4 windows.  I closed one of each window after making sure that the tab groups wouldn't be affected.  Starting with the next time I restarted, it started duplicating the entire session in the hidden unsynchronous tabs menu.  It does this most of the time when Firefox restarts, but not every time.  I have no idea what makes it happen or not.

**Comment by 29988122** [comment]
I can confirm also recreate this issue.

Simply by close firefox normally -> restart will cause this to happen.

**Comment by Drive4ik** [comment]
@29988122 Do you use latest version of STG? Do you has enabled checkbox "restore session" in browser settings?

**Comment by 29988122** [comment]
>version
Yes, the latest version, dated 03/14.
>restore session
Yes, I ticked that option.

I'll perform anything useful for you to fix, feel free to ask. (Sorry, I'm unable to understand the codebase of STG, thus not able to trace it)

**Comment by Drive4ik** [comment]
@29988122 Could you video record the behavior of this error?
https://www.screentogif.com/

**Comment by PJTraill** [comment]
I seem to have this problem too, or something like it and/or #385 and/or #448 . I end up with masses of hidden tabs, some of them multiple times, and it seems that when I close tabs they just end up hidden. It offers to put hidden tabs in a new group, but it does not seem to see all of them. I am not sure if it is also confused by multiple windows.

**Comment by Drive4ik** [comment]
@PJTraill Unfortunately, not everything always works or ends normally, as we expect.
I repeat a little (already wrote in other tickets), the link group - tab is not stored in the addon, but in the browser session. Therefore, if the addon does not see this connection, then the browser session did not save it ... I will of course look at the add-on and synchronization initialization code, and possibly improve it.

**Comment by 29988122** [comment]
I'm not able to reproduce this behavior recently.

Anyway, your work is a great addon in the WebExtention Era - nothing can replace it.
Thank you for everything you'd ever done!

**Comment by ACB1337** [comment]
I also have this issue. But I noticed that when I disable "Allow access to bookmarks" in the extension options it does not occur. So there may be a problem there.

**Comment by Drive4ik** [comment]
Hello everyone. I fixed this bug, please wait for the next release. But there is another bug that I can’t fix yet, the FF bug, for some reason it does not remember the containers of open tabs in this scenario. That is, it creates tabs with the correct containers, but after restarting the browser, they all become without containers. I will create an FF bug.

**Comment by grahamperrin** [comment]
> … restarting the browser, …

Using the **Restart** feature of Firefox?

![image](https://user-images.githubusercontent.com/192271/109410254-0c638680-7991-11eb-8905-835f442c54c4.png)

**Comment by grahamperrin** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/347#issue-419626517

> … often … for some reason dump …

> To reproduce: Restart Firefox.

> * Firefox version: 65.0.2

Above, with _many_ other extensions enabled, I can not reproduce an issue with a restart of Firefox. 

> … The first time this happened was the next restart after a Firefox crash. …

> … most of the time when Firefox restarts, …

@notJerl please: is your Firefox `86.0` more reliable?

If you find no problem with Simple Tab Groups alone enabled **and Firefox _not_ crashing**: 

* I suggest closing this issue
 
– thanks. Then: 

* if you suspect anything like an extensions conflict, you can raise a new issue (with a list of enabled extensions – use [Add-on List-o-matic 9000](https://addons.mozilla.org/addon/add-on-list-o-matic-9000/))
* if you find Firefox crashing (or silently failing to exit/quit cleanly, which can be equally troublesome to extensions) find or create a bug with Mozilla – https://bugzilla.mozilla.org/

**Comment by notJerl** [comment]
@grahamperrin Drive4ik said that there was another issue, so I presume that's why the ticket got left open instead of closed.  I'm not going to close a ticket that might still have an issue that the developer might be working on, especially since I never ran into the issue he described.

**Comment by grahamperrin** [comment]
@notJerl no argument, thanks for responding. 

_Do_ you no problem with Simple Tab Groups alone enabled **and Firefox _not_ crashing**?
