### ISSUE TITLE
Random tabs just dissappear from Tab groups

### ISSUE THREAD

**Issue by ShaunMav** [Drive4ik/simple-tab-groups#70]
Do the simple test of switching between groups, shutting FF down, restarting, switching groups. This simple test very quickly reveals this unfortunate bug - tabs just disappear.

To test, I create one tab group with known number of tabs, I just use 3 or so. I then switch between this and another tab group with many tabs (no need to note number of tabs in this group, but likely same thing is happening). 

Now, simply switch between the two tab groups, select different tabs within the group. Sometimes already the issue shows. If not, shut down FF, open and repeat simple switching between tabs and tab groups. You will see that slowly you end up with no tabs remaining in the group that had 3 tabs.

Also try adding one new tab to the group of three, then remove it, and continue switching/restarting FF. You will see that slowly you end up with no tabs remaining in the group that had 3 tabs.

Hope this helps, thank you.

**Comment by Tyrewt** [comment]
@ShaunMav sounds a lot like #62 , please confirm you are using the latest Add-on build (2.3.6)?

**Comment by shaunmavronicolas** [comment]
No, this is not quiet the same. Please try the simple test I outlined above to see just what I am talking about. Randomly loosing tabs in a group is not something I understood from ticket #62, especially simply when switching back and forth, sometimes no tabs are lost, other times tabs a lost, without restarting, though restarting might aggravate the underlying issue. Thank you.

**Comment by Tyrewt** [comment]
@shaunmavronicolas 2.3.6?

**Comment by ShaunMav** [comment]
![screen shot 2018-01-31 at 6 14 33 pm](https://user-images.githubusercontent.com/36011691/35657748-fc7a0c98-06b2-11e8-91a5-e64a21120261.png)

Correct.

**Comment by Tyrewt** [comment]
@ShaunMav @Drive4ik I have confirmed this behavior, though in my case at a lesser frequency.

Using the same backup.zip as last time, I imported a regular backup which created 3 Groups with 4 Tabs within each. Switching between Groups randomly and closing Firefox, after about 6 attempts, Group 2 lost 3 of the 4 Tabs, brining the total down to 1.

- Firefox 58.0.1
- Simple Tab Groups 2.3.6
- https://github.com/Drive4ik/simple-tab-groups/files/1670687/quicksaver-tab-groups-backups.zip

**Comment by ShaunMav** [comment]
I have an extensive Tab group arrangement as you will see below. It is possible that this causes a far higher frequency of vanishing tabs. In all the years I used Tab Groups I never lost one tab. I made frequent backups and still do, never lost a thing, it has been indespensible and I do not see why what is currently here cannot do the same :-)

![screen shot 2018-01-31 at 8 35 50 pm](https://user-images.githubusercontent.com/36011691/35661421-e761fb2c-06c6-11e8-976e-f461c98e51ce.png)

**Comment by Drive4ik** [comment]
Hi all
I still can not understand why this is happening, but I can definitely say that this browser problem ...
I'll try to fix this so that the tabs are not lost if the browser itself has closed some tabs at startup.

I ask to see a long animation demonstrating this problem.
also please note that the fast download of tabs is disabled, and (when you look at the animation) before restarting the browser all 4 tabs were loaded, but after running them there were 3 instead of 4
addon was disabled before browser restart

animation lasts more than 1 minute
![missed-tabs-bug](https://user-images.githubusercontent.com/7843031/35680587-7aa14a9a-0763-11e8-9f68-bfb506af4a97.gif)

What do you think about it?

**Comment by shaunmavronicolas** [comment]
I can repeat this problem much faster - so with less much less switching and no need to switch fast, just normal speed. 

Instead of just switching as you are doing, add and remove tabs within a group while keeping track of this, just add or move or remove one tab and then switch groups, you will see this problem happen much faster. Also, restarting browser creates the problem.

Maybe with this test you will find real cause? Anything is possible, maybe add-on, maybe browser, I do not know how to test this thoroughly.

**Comment by Drive4ik** [comment]
Hi all.
I do not know what to call it, but with mozilla something happens.
![ff-missed-tabs](https://user-images.githubusercontent.com/7843031/35703913-6e345c78-07a6-11e8-8ff4-1c6c151e98c4.gif)

this is a very serious problem

**Comment by Tyrewt** [comment]
I think we all agree this is a major issue which renders the add-on not usable. I don't even trust the Tab count on Groups anymore as this seems to be incorrect too.

@Drive4ik FYI. seems most comments here are English, can you switch the screencast language next time?  

In the last screencast from @Drive4ik , no Group switching takes place and yet the Tabs are lost/out of sync. I can help test, but truly do not know what the cause is.

**Comment by Drive4ik** [comment]
@Tyrewt 
this is not a STG bug, this if FF bug. In gif above STG not installed.

about "screen cast language in English": I will try to make gif in English :) (I neglected it, because everything is clear there and so)

I created a bug in bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1435077

What do you mean by the count of tabs, I did not notice this with problems.
If you can, please record issue (count of tabs) to GIF animation
http://www.screentogif.com/

**Comment by Tyrewt** [comment]
@Drive4ik okay, I understand the gif now. Thanks.

The Tab count wasn't updating on the Group I have open (Group 1). Opening and closing Tabs did not affect the total count shown in the menu. As we initially thought switching Groups had something to do with the overall issue, I have been avoiding switching Groups. 

As a test, I went to the menu and selected the same Group I've been keeping open (Group 1), it gave me the  "Load this group will close all current Tabs!" warning and reloaded. Total Tab count is now working again. Maybe something was stuck, I'll keep an eye on it.

**Comment by Drive4ik** [comment]
Group and window synchronization logic
If the tabs of the window completely coincide with the tabs in the group
or the tabs of the window are bigger and they also coincide (there are extra) - the window and the group are synchronized

eg
If you have 5 tabs in a synchronized group, you can disable the addon and then close one of the tabs. After the addon is turned on, the group does not synchronize, since the tabs and their number do not match.
but you will add one or more tabs, and then enable the add-on - synchronization will occur because it is possible to launch the browser from a link from another program, and therefore, when browsing, the browser has more than one tab.

But it will all work if the browser itself does not close the tabs, as I showed on the gif above.
now also a lot of bad reviews on this add-on write, although this is a browser problem.

**Comment by Tyrewt** [comment]
@Drive4ik so there is nothing we can do in the browser options to prevent this? Maybe you should update the Add-on page saying there is a bug in Firefox and link to the report. That will help with negative reviews.

Your Add-on is the best solution I've tested, hopefully we can get some attention on a fix with Firefox.

**Comment by Drive4ik** [comment]
@Tyrewt Yes, I have already updated the description on the add-on page
Thank you for your help!

**Comment by shaunmavronicolas** [comment]
I am glad you have been able to get deeper into things, I think this is a very good step forward and I will withdraw my last review, now that I have a better understanding that there is some deeper issue happening at the FF core.

**Comment by Drive4ik** [comment]
@shaunmavronicolas No one without a flaw, and FF including :)

**Comment by Jaxx005** [comment]
Some info that my help...  I have found that on occassions:
**ALL open tabs are 'disassociated' with a group** 
Steps/cause: 
- PC unattended:  left logged on, FF running (FF might have been restarted and tabs autoloaded?)
- returned to PC, screens lit up (not locked), maximised FF, switched tab groups...
- Got the warning ""Load this group will close all current Tabs!"
- So, cancelled this (did not change group)
- No group name shown when hovering over SimpleTabGroup menu icon (was expecting "Misc")
- Also, in Manage Groups:  "Misc" group showed tabs seemingly identical to those open in FF*
  (seemingly confirming that they were the tabs that were once in my "Misc" tab group)

*No loss of tabs in this case, but had any new tabs been opened, these would have been lost when switching tab groups?  Certainly I have lost tabs in the past, and now I suspect the issue(s) above might be the cause (I ignored the warning message initially).

Hope info helps. Does seem related to main topic, and I note reference to #53 mentioned above. 

Awesome work btw :)

**Comment by Tyrewt** [comment]
@Drive4ik Maybe edit the wording on the Add-on page, encouraging people to go "vote" the [Firefox Bug up, this stresses the importance of a fix](https://bugzilla.mozilla.org/show_bug.cgi?id=1435077)

**Comment by irvinm** [comment]
There is a bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1427007) that has to do with session store problems on exit that was fixed recently that will land in Firefox 60.  I believe it should already be in the current builds of 60.  Can someone retry this issue with 60?  Maybe it is already fixed.

**Comment by Tyrewt** [comment]
Now that Firefox 60 has been released, can anyone confirm the issue with Tabs is present or not?

**Comment by fujisyugi** [comment]
@Tyrewt I am having this issue/bug still.

**Comment by Tyrewt** [comment]
@fujisyugi Firefox version 60?  I did some quick testing and didn't experience the issue.

@Drive4ik can try FF v60 and perform the same test you did when submitting [Firefox Bug 1435077](https://bugzilla.mozilla.org/show_bug.cgi?id=1435077)?

**Comment by Drive4ik** [comment]
@Tyrewt this bug still replicated...

![missed-tabs-31 05 2018](https://user-images.githubusercontent.com/7843031/40783544-6ce7ec20-64eb-11e8-8dcf-03c616f9c2e5.gif)

**Comment by Tyrewt** [comment]
@Drive4ik The Mozilla bug report you submitted 4 months ago has: [Status (NEW bug which is in the backlog (and should be changed to a P3) awaiting an answer on a request for information)](https://bugzilla.mozilla.org/show_bug.cgi?id=1435077).

This is a critical data loss issue, perhaps you can post there to follow up?

**Comment by Tyrewt** [comment]
@Drive4ik I was under the understanding that the issue was solely with Firefox, what was it that you fixed?

**Comment by bp-git** [comment]
@Drive4ik 
I am using STG 3.4.2.1 on Opensuse+Current_Firefox(65.0.1). 
I also use Tree_Style_Tab, JavaScript On/Off & You_Tube Lightweight Flash Player.

I have 12 tab groups defined. I set them up, and then did a backup. It ran fine for about 1 month
then corrupted somehow. I can switch between tab groups, but when a select a specific tab
it then jumps to another tab in another tab group. So, I can not properly navigate. After I did that it also reported unlinked tabs, which I discarded per one of the available options. 

I tried to debug as follows.
1. Deactivate STG.
2. Reactivate STG.
3. Import saved backup.

This did not solve the problem. I considered eliminating all tab groups and recreating them, but 
I am afraid that I would end up in the same corrupted place w/ no obvious fix.

Please tell me how to properly recover from this state and if you want any debugging info
from my setup. I really, really like the program, I just need it to work reliably. 
Thx! 
BP

**Comment by Drive4ik** [comment]
@bp-git Hey. Try to remove the addon, restart the browser and install it again, and then restore the backup.
If you can - send a screenshot or a video with an error
