### ISSUE TITLE
Backups should not be saved to downloads

### ISSUE THREAD

**Issue by baterflyrity** [Drive4ik/simple-tab-groups#778]
**Describe the bug**
Despite closed #284 automatic backups are saved to `/path/to/Downloads/STG-backups-FF-<Firefox version>/` directory while they should be placed in Mozilla profile.

**To Reproduce**
1. Go to add-on settings.
2. Go to backups tab.
3. Enable automatic backups.
4. Check your `/path/to/Downloads/` directory in a while.

**Expected behavior**
Downloads directory should be empty but it is flooded with backups.

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 85.0.2
 - Simple Tab Groups version: 4.7

**Comment by grahamperrin** [comment]
> flooded 

One directory (folder) per version of Firefox. Are things not filed in that way for you?

https://github.com/Drive4ik/simple-tab-groups/commit/7b63c795445514063bbfc6132a0946f28c32efaa#diff-5635b9ed75e6466995bcf7dc6eab586a9a05e1264d452f6fe04de6fae2b9527eR92

**Comment by baterflyrity** [comment]
@grahamperrin according to #284 this folder should be saved in another path. So I always see random folders with random files in my downloads which are obviously for downloaded data but configuration one. Hence all my environment, scripts and workflow is balked at this point.

**Comment by grahamperrin** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/284#issuecomment-456161552 refers to <https://github.com/Drive4ik/simple-tab-groups/issues/314>, which was fixed by https://github.com/Drive4ik/simple-tab-groups/commit/7b63c795445514063bbfc6132a0946f28c32efaa (2019-01-21) involving three files, each of which has a more recent edition: 

* https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/js/constants.js
* https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/js/file.js
* https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/options/Options.vue

For automated backups, _downloads_ is the expected location for each version-specific backup folder: 

![image](https://user-images.githubusercontent.com/192271/108595291-ffcea500-7376-11eb-8bc2-ff21a7146773.png)

**Comment by baterflyrity** [comment]
@grahamperrin ,

> I partially fixed this issue in #314 , and fix failed downloads in #313

Read carefully, only the smallest part of the problem has been fixed. But main idea of changing directory has been just ignored and closed?! Well... its not serious approach.

**Comment by grahamperrin** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/284#issue-377112184 @dchmelik wrote: 

>> … rather than root of the user's home directory …

☑ Simple Tab Groups no longer backs up to `~` 

> … main idea of changing directory has been just ignored …

The path did change. Simple Tab Groups no longer backs up to `~`

**Comment by grahamperrin** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/284#issuecomment-435845493

> Webextension does not allow you to change the folder for downloading

Has Mozilla altered the restriction?

**Comment by baterflyrity** [comment]
@grahamperrin I dont know.  What about  IndexedDB file storage library? Nevertheless, the problem is still persistent.

**Comment by grahamperrin** [comment]
From https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download for `filename`:

> … relative to the default downloads directory … Absolute paths, … and paths containing back-references (../) will cause an error. …

**Comment by grahamperrin** [comment]
> IndexedDB file storage library

Would that allow each backup file to be found (without Firefox) by a file manager?

**Comment by baterflyrity** [comment]
> 
> 
> > IndexedDB file storage library
> 
> Would that allow each backup file to be found (without Firefox) by a file manager?

In profile directory each add-on has own directory with sqlite base and other cached items. I didnt investigate availability to reuse this files manually.

**Comment by tobiasdiez** [comment]
I agree, saving the backups in the download folder is irritating (especially as it took me some time to realize that STG = this firefox addon I'd installed a few weeks ago). I think, `storage.local` is meant for this purpose: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage

**Comment by R-Usher** [comment]
Current naming convention completely ignores users with multiple profiles. By default user profile name should be used as a part of backup folder name, I think.

**Comment by grahamperrin** [comment]
> Current naming convention completely ignores users with multiple profiles.

I use multiple profiles. 

The path to the profile includes the name; this is by Mozilla's design.

**Comment by R-Usher** [comment]
It's misunderstanding.
A single Windows user has only one Download folder. If STG keeps its backups in the Download folder, then it will systematically overwrite a backup created for just closed Firefox profile with a backup created for another, freshly open Firefox profile. I DID test it before posting a message.

**Comment by grahamperrin** [comment]
Ah, thanks for the clarification. I never encountered overwrite, maybe because I prefer hourly backups; each backup is distinctively named, for example: 

`auto-stg-backup-2021-03-28~18-37@drive4ik.json`

**Comment by R-Usher** [comment]
Hourly backup is neither set by default nor perfect. Users have to open backups and guess which backup comes from which Firefox profile.

**Comment by tobiasdiez** [comment]
May I point again towards `storage.local`, which would fix this name conflicts as well.

**Comment by nekohayo** [comment]
Hi folks,
Personally, as a user, I'm not losing sleep at the existence of the "STG-backups" folder (whose name is configurable anyway) in my Downloads folder, and if I really cared about not visually seeing it in that folder, I could make it a hidden folder...

If you really care deeply about this particular issue, as you seem to know what can/cannot be done by web extensions in terms of storage, at this point now it might be a good idea for one of you to help the maintainer by offering a patch / pull request for this.

**Comment by baterflyrity** [comment]
@nekohayo , hi. Unfortunately i dont know storage api so cant push fix. 

Also you suggestion to hide directory is not so bad, thanks, but hide problem != solve problem. 

Moreover want to notice that when #284 was closed the problem was not solved. So the maintainer just ignored community without further designation :(

**Comment by baterflyrity** [comment]
In addition to @nekohayo [solution](https://github.com/Drive4ik/simple-tab-groups/issues/778#issuecomment-823770764) as an alternative temporary one i can suggest disabling whole backup system.

**Comment by dchmelik** [comment]
Looks like they should be saved in .mozilla/firefox/profile/storage/default/moz-extension+++be65bfdf-bc01-4340-87bd-f4dbbede7d91 .

**Comment by repparw** [comment]
I arrived at this issue because I noticed you can't use folders starting with a dot (like .stg, so, a hidden folder on Linux) even on Downloads folder. I don't know if that's a limitation of webextensions or not, but I would like to use a hidden folder, then I can make a symlink to a folder on another place and I don't have to see the backups on Downloads.

**Comment by Drive4ik** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/778#issuecomment-783177257

**Comment by tobiasdiez** [comment]
@Drive4ik https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage This would also make things easier as you don't need to worry about the actual (de)serialization of the stuff to a file; this is handled by the browser.

**Comment by baterflyrity** [comment]
> 
> 
> [#778 (comment)](https://github.com/Drive4ik/simple-tab-groups/issues/778#issuecomment-783177257)

Well... I believe you should tag this issue as "Wont fix" because in my mind closed and unresolved issues are different.

**Comment by nekohayo** [comment]
Additional info from https://github.com/Drive4ik/simple-tab-groups/issues/1005#issuecomment-1500909947 :

> Sometimes, and sometimes every part of Firefox crashes, and you lose your whole profile. Including bookmarks, passwords and addon settings that save data in the profile using the `storage` API.

Furthermore, from https://github.com/Drive4ik/simple-tab-groups/issues/1012#issuecomment-1500903799 we can see this might become even more difficult with the "Manifest v3" extensions API, the "localStorage" reportedly has a 5/10 MB memory limit.

Since people keep bringing up this issue, maybe the preferences UI should also have a "Why does it save backups into the Downloads folder?" hyperlink to a FAQ entry somewhere (ex: a markdown file in this github repository?) where there is the complete explanation from copy-pasting the various technical answers to this.

**Comment by baterflyrity** [comment]
@nekohayo , very nice idea. It would be great to see a tooltip like "this bug downstreams from firefox limitation".

**Comment by Jellby** [comment]
Annoyingly, I have the download folder set to `/tmp` (I don't want my filesystem clogged with temporary downloads that I never look at again), which results in the backups ending up in `/tmp` too, and being wiped at system reboot... not very useful backups, I'd say.

**Comment by nekohayo** [comment]
@Jellby I think you'll agree that's a very niche / uncommon usage pattern, and not something STG can do much about given the aforementioned API constraints. In your particular edge case, you could work around this by having some cron job that periodically copies your backups from that location to some other location of your choosing. Or include it in your backup scripts (or backup software's target locations) in the first place (as I can imagine you certainly have backup systems in place, instead of trusting your /home partition to never fail).

**Comment by baterflyrity** [comment]
> @Jellby I think you'll agree that's a very niche / uncommon usage pattern, and not something STG can do much about given the aforementioned API constraints. In your particular edge case, you could work around this by having some cron job that periodically copies your backups from that location to some other location of your choosing. Or include it in your backup scripts (or backup software's target locations) in the first place (as I can imagine you certainly have backup systems in place, instead of trusting your /home partition to never fail).

@Jellby , In your particular edge case, you could write your own alternative of STG as backups of STG is not responsibility of STG 🤹

**Comment by shalom938** [comment]
On linux too, I didn't read all the details but it sounds very strange that Downlods is selected as backup folder for a firefox extension, every time i see these folders i have to waste another 15 minutes just to realize what is it and to remember that i already did it a week ago.
very irritating.  more then 2 years and not fixed. I guess the best solution is to uninstall.

**Comment by grahamperrin** [comment]
> … I guess the best solution is to uninstall.

Please don't overreact. 

If backups are (understandably) important to you, it makes no sense to effectively discard what you wanted to backup.

**Comment by grahamperrin** [comment]
> Annoyingly, I have the download folder set to `/tmp` (I don't want my filesystem clogged with temporary downloads) …

Do you mean that you never kept anything that you downloaded?

**Comment by Jellby** [comment]
> Do you mean that you never kept anything that you downloaded?

Most of the stuff, no. PDFs and other files that I open with external programs, go to the download folder; once I've viewed them, I have no more use for them, although sometimes I open them again. Other things I want to keep, I make sure I place them where they belong (at download time, or after), which is not a single download folder for everything.

**Comment by dchmelik** [comment]
I don't use/keep a downloads directory/folder so just had to stop using Simple Tab Groups.

**Comment by scarlion1** [comment]
Yoo @Jellby bro `/tmp` crew represent!

<ins>𝒲ℴ𝓇𝓀𝒶𝓇ℴ𝓊𝓃𝒹</ins>
(retain backup data in `/tmp` + store backups in profile dir + allow backup of _STG_ from multiple profiles)

1. `mkdir ~/.mozilla/firefox/<FFprofile.name>/stg-backup`
2. `ln -s ~/.mozilla/firefox/<FFprofile.name>/stg-backup /tmp/stg-backup-<FFprofile.name>`
3. Change _STG_ backup folder to `stg-backup-<FFprofile.name>`.  Click Open Folder button to make sure it can open.
4. Create `/etc/tmpfiles.d/stg-backup.conf`:
```
#Type	Path			Mode	User	Group	Age	Argument
#Ignore (exclude (recursively)) /tmp/stg-backup* during cleaning
x	/tmp/stg-backup*	-	-	-	-	-
```

1-3 can be used to redirect backups from any downloads location, just change `/tmp` in step2 to your download dir.  The new symbolic link will redirect backups to your profile dir.  Can create a link for each profile you have _STG_ installed in.  The config file in step4 should prevent _systemd-tmpfiles_ from deleting the link and everything it points to?  Untested.  Will write back if I have any issues.  🎉
